### ISSUE TITLE
Classes: CSE classes tend to get full

### ISSUE THREAD

**Issue by emikoifish** [bioinfo-ucsd/BISB-Bootcamp-2022#9]
In [Onboarding](https://bioinfo-ucsd.github.io/BISB-Bootcamp-2022/ucsd-onboarding/), it says that it is not urgent to enroll in classes, which is mostly true, however, CSE is impacted so some of their classes tend to fill up quickly.

**Comment by mikecuoco** [comment]
@emikoifish feel free to reopen if you think more language should be added
